// NOTE: Do not edit this file. It is built by running `./build/create-mockup-pages.js`
// NOTE: Generated at 2018-11-19T01:15:18.743Z
import LogPage from './log-page';
import ExamplePage from './example-page';

export default [
  {
    title: 'Annet',
    pages: [
      {
        component: LogPage,
        name: 'L',
        url: '/log-page'
      }
    ]
  },
  {
    title: 'Eksempelgruppe',
    pages: [
      {
        component: ExamplePage,
        name: 'eksempelside',
        url: '/example-page'
      }
    ]
  }
];
